name: Generate Organist Schedule

on:
  schedule:
    - cron: "0 23 * * *"   # 23:00 UTC = 06:00 WIB
  workflow_dispatch:       # Bisa dijalankan manual

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scripts
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          export PYTHONPATH="${PYTHONPATH}:$(pwd)"
          python scripts/generate_vincent_schedule.py
